# Constants of the solution

MINUTE = "MINUTE"
HOUR = "HOUR"
DAY_OF_MONTH = "DAY_OF_MONTH"
MONTH = "MONTH"
DAY_OF_WEEK = "DAY_OF_WEEK"
COMMAND = "COMMAND"

# Cron Component Classification Keys
WILDCARD = "WILDCARD"
COMMA = "COMMA"
RANGE = "RANGE"
DIVISION = "DIVISION"
NO_PROCESSING = "NO_PROCESSING"
